function validateLinearPlant(linearPlant, simulationPlan)
    % VALIDATELINEARPLANT Validates linear plant struct produced by buildLinearPlant.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % INPUTS
    %  linearPlant     (struct) - linearized plant model
    %  simulationPlan  (struct) - source simulation plan used to build plant
    %
    % OUTPUT
    %  None. Function throws assertion error on invalid input.

    %%%%%%%%%%%%%%%%%%%%%
    % TOP-LEVEL CHECKS  %
    %%%%%%%%%%%%%%%%%%%%%
    assert(isstruct(linearPlant), ...
        'validateLinearPlant:InvalidType', ...
        'linearPlant must be a struct.');

    requiredTopLevelFields = {'A', 'B', 'E', 'metadata'};
    actualTopLevelFields = fieldnames(linearPlant);

    assert(all(isfield(linearPlant, requiredTopLevelFields)), ...
        'validateLinearPlant:MissingField', ...
        'linearPlant is missing one or more required fields: A, B, E, metadata.');

    assert(numel(actualTopLevelFields) == numel(requiredTopLevelFields), ...
        'validateLinearPlant:UnexpectedFieldCount', ...
        'linearPlant contains unexpected top-level fields.');

    %%%%%%%%%%%%%%%%%%%%%
    % MATRIX VALIDATION %
    %%%%%%%%%%%%%%%%%%%%%
    validateattributes(linearPlant.A, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [2, 2]}, ...
        mfilename, 'linearPlant.A');

    validateattributes(linearPlant.B, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [2, 2]}, ...
        mfilename, 'linearPlant.B');

    validateattributes(linearPlant.E, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [2, 3]}, ...
        mfilename, 'linearPlant.E');

    %%%%%%%%%%%%%%%%%%%%%
    % METADATA CHECKS   %
    %%%%%%%%%%%%%%%%%%%%%
    assert(isstruct(linearPlant.metadata), ...
        'validateLinearPlant:InvalidMetadataType', ...
        'linearPlant.metadata must be a struct.');

    requiredMetadataFields = {'operatingPoint', 'plantGeometry', 'physicalConstants'};
    actualMetadataFields = fieldnames(linearPlant.metadata);

    assert(all(isfield(linearPlant.metadata, requiredMetadataFields)), ...
        'validateLinearPlant:MissingMetadataField', ...
        ['linearPlant.metadata is missing one or more required fields: ', ...
         'operatingPoint, plantGeometry, physicalConstants.']);

    assert(numel(actualMetadataFields) == numel(requiredMetadataFields), ...
        'validateLinearPlant:UnexpectedMetadataFieldCount', ...
        'linearPlant.metadata contains unexpected fields.');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % OPERATING POINT SUBSTRUCT CHECK %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    operatingPoint = linearPlant.metadata.operatingPoint;

    assert(isstruct(operatingPoint), ...
        'validateLinearPlant:InvalidOperatingPointType', ...
        'linearPlant.metadata.operatingPoint must be a struct.');

    requiredOperatingPointFields = {'K', 'vW', 'hT', 'hM', 'Qladle', 'uM'};
    actualOperatingPointFields = fieldnames(operatingPoint);

    assert(all(isfield(operatingPoint, requiredOperatingPointFields)), ...
        'validateLinearPlant:MissingOperatingPointField', ...
        ['linearPlant.metadata.operatingPoint is missing one or more required ', ...
         'fields: K, vW, hT, hM, Qladle, uM.']);

    assert(numel(actualOperatingPointFields) == numel(requiredOperatingPointFields), ...
        'validateLinearPlant:UnexpectedOperatingPointFieldCount', ...
        'linearPlant.metadata.operatingPoint contains unexpected fields.');

    for iField = 1:numel(requiredOperatingPointFields)
        fieldName = requiredOperatingPointFields{iField};
        validateattributes(operatingPoint.(fieldName), {'double'}, ...
            {'real', 'finite', 'nonsparse', 'scalar'}, ...
            mfilename, ['linearPlant.metadata.operatingPoint.', fieldName]);
    end

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % PLANT GEOMETRY SUBSTRUCT CHECK %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    plantGeometry = linearPlant.metadata.plantGeometry;

    assert(isstruct(plantGeometry), ...
        'validateLinearPlant:InvalidPlantGeometryType', ...
        'linearPlant.metadata.plantGeometry must be a struct.');

    requiredPlantGeometryFields = { ...
        'moldCrossSectionWidth', ...
        'moldCrossSectionLength', ...
        'moldCrossSectionalArea', ...
        'moldAxialLength', ...
        'nozzleCrossSectionalArea', ...
        'tundishCrossSectionalArea'};

    actualPlantGeometryFields = fieldnames(plantGeometry);

    assert(all(isfield(plantGeometry, requiredPlantGeometryFields)), ...
        'validateLinearPlant:MissingPlantGeometryField', ...
        ['linearPlant.metadata.plantGeometry is missing one or more required ', ...
         'fields.']);

    assert(numel(actualPlantGeometryFields) == numel(requiredPlantGeometryFields), ...
        'validateLinearPlant:UnexpectedPlantGeometryFieldCount', ...
        'linearPlant.metadata.plantGeometry contains unexpected fields.');

    for iField = 1:numel(requiredPlantGeometryFields)
        fieldName = requiredPlantGeometryFields{iField};
        validateattributes(plantGeometry.(fieldName), {'double'}, ...
            {'real', 'finite', 'nonsparse', 'scalar', 'positive'}, ...
            mfilename, ['linearPlant.metadata.plantGeometry.', fieldName]);
    end

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % PHYSICAL CONSTANTS SUBSTRUCT CHECK %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    physicalConstants = linearPlant.metadata.physicalConstants;

    assert(isstruct(physicalConstants), ...
        'validateLinearPlant:InvalidPhysicalConstantsType', ...
        'linearPlant.metadata.physicalConstants must be a struct.');

    requiredPhysicalConstantsFields = {'g'};
    actualPhysicalConstantsFields = fieldnames(physicalConstants);

    assert(all(isfield(physicalConstants, requiredPhysicalConstantsFields)), ...
        'validateLinearPlant:MissingPhysicalConstantsField', ...
        'linearPlant.metadata.physicalConstants must contain field g.');

    assert(numel(actualPhysicalConstantsFields) == numel(requiredPhysicalConstantsFields), ...
        'validateLinearPlant:UnexpectedPhysicalConstantsFieldCount', ...
        'linearPlant.metadata.physicalConstants contains unexpected fields.');

    validateattributes(physicalConstants.g, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'scalar', 'positive'}, ...
        mfilename, 'linearPlant.metadata.physicalConstants.g');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % CONSISTENCY CHECKS AGAINST SOURCE PLAN      %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    assert(isstruct(simulationPlan), ...
        'validateLinearPlant:InvalidSimulationPlanType', ...
        'simulationPlan must be a struct.');

    requiredSimulationPlanFields = {'operatingPoint', 'plantGeometry', 'physicalConstants'};
    assert(all(isfield(simulationPlan, requiredSimulationPlanFields)), ...
        'validateLinearPlant:SimulationPlanMissingField', ...
        ['simulationPlan must contain operatingPoint, plantGeometry, and ', ...
         'physicalConstants for validation.']);

    assert(isequal(linearPlant.metadata.operatingPoint, simulationPlan.operatingPoint), ...
        'validateLinearPlant:OperatingPointMismatch', ...
        ['linearPlant.metadata.operatingPoint must exactly match ', ...
         'simulationPlan.operatingPoint.']);

    assert(isequal(linearPlant.metadata.plantGeometry, simulationPlan.plantGeometry), ...
        'validateLinearPlant:PlantGeometryMismatch', ...
        ['linearPlant.metadata.plantGeometry must exactly match ', ...
         'simulationPlan.plantGeometry.']);

    assert(isequal(linearPlant.metadata.physicalConstants, simulationPlan.physicalConstants), ...
        'validateLinearPlant:PhysicalConstantsMismatch', ...
        ['linearPlant.metadata.physicalConstants must exactly match ', ...
         'simulationPlan.physicalConstants.']);
end