function validateMeasurementModel(measurementModel, simulationPlan)
    % VALIDATEMEASUREMENTMODEL Validates measurement model struct produced by
    % buildMeasurementModel.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % INPUTS
    %  measurementModel (struct) - measurement model for simulation pipeline
    %  simulationPlan    (struct) - source simulation plan
    %
    % OUTPUT
    %  None. Function throws assertion error on invalid input.

    %%%%%%%%%%%%%%%%%%%%%
    % TOP-LEVEL CHECKS  %
    %%%%%%%%%%%%%%%%%%%%%
    assert(isstruct(measurementModel), ...
        'validateMeasurementModel:InvalidType', ...
        'measurementModel must be a struct.');

    requiredTopLevelFields = {'observabilityCase', 'C', 'D'};
    actualTopLevelFields = fieldnames(measurementModel);

    assert(all(isfield(measurementModel, requiredTopLevelFields)), ...
        'validateMeasurementModel:MissingField', ...
        ['measurementModel is missing one or more required fields: ', ...
         'observabilityCase, C, D.']);

    assert(numel(actualTopLevelFields) == numel(requiredTopLevelFields), ...
        'validateMeasurementModel:UnexpectedFieldCount', ...
        'measurementModel contains unexpected top-level fields.');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % SIMULATION PLAN CHECKS    %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    assert(isstruct(simulationPlan), ...
        'validateMeasurementModel:InvalidSimulationPlanType', ...
        'simulationPlan must be a struct.');

    assert(isfield(simulationPlan, 'observabilityCase'), ...
        'validateMeasurementModel:SimulationPlanMissingField', ...
        'simulationPlan must contain field observabilityCase.');

    assert(isstring(measurementModel.observabilityCase) || ischar(measurementModel.observabilityCase), ...
        'validateMeasurementModel:InvalidObservabilityCaseType', ...
        'measurementModel.observabilityCase must be a string scalar or character vector.');

    observabilityCase = string(measurementModel.observabilityCase);
    sourceObservabilityCase = string(simulationPlan.observabilityCase);

    assert(isscalar(observabilityCase) && strlength(observabilityCase) > 0, ...
        'validateMeasurementModel:InvalidObservabilityCaseShape', ...
        'measurementModel.observabilityCase must be a nonempty string scalar.');

    allowedObservabilityCases = ["full", "moldOnly"];
    assert(any(observabilityCase == allowedObservabilityCases), ...
        'validateMeasurementModel:UnsupportedObservabilityCase', ...
        'measurementModel.observabilityCase must be either "full" or "moldOnly".');

    assert(observabilityCase == sourceObservabilityCase, ...
        'validateMeasurementModel:ObservabilityCaseMismatch', ...
        ['measurementModel.observabilityCase must exactly match ', ...
         'simulationPlan.observabilityCase.']);

    %%%%%%%%%%%%%%%%%%%%%
    % MATRIX VALIDATION %
    %%%%%%%%%%%%%%%%%%%%%
    validateattributes(measurementModel.C, {'double'}, ...
        {'real', 'finite', 'nonsparse', '2d'}, ...
        mfilename, 'measurementModel.C');

    validateattributes(measurementModel.D, {'double'}, ...
        {'real', 'finite', 'nonsparse', '2d'}, ...
        mfilename, 'measurementModel.D');

    switch observabilityCase
        case "full"
            validateattributes(measurementModel.C, {'double'}, ...
                {'size', [2, 2]}, ...
                mfilename, 'measurementModel.C');

            validateattributes(measurementModel.D, {'double'}, ...
                {'size', [2, 2]}, ...
                mfilename, 'measurementModel.D');

            assert(isequal(measurementModel.C, eye(2)), ...
                'validateMeasurementModel:InvalidFullStateC', ...
                'For observabilityCase "full", measurementModel.C must equal eye(2).');

            assert(isequal(measurementModel.D, zeros(2, 2)), ...
                'validateMeasurementModel:InvalidFullStateD', ...
                'For observabilityCase "full", measurementModel.D must equal zeros(2,2).');

        case "moldOnly"
            validateattributes(measurementModel.C, {'double'}, ...
                {'size', [1, 2]}, ...
                mfilename, 'measurementModel.C');

            % I am intentionally holding D to 1x2 here because y is scalar in
            % the moldOnly case, so dimensional consistency of y = Cx + Du
            % demands D be 1x2 rather than 2x2.
            validateattributes(measurementModel.D, {'double'}, ...
                {'size', [1, 2]}, ...
                mfilename, 'measurementModel.D');

            assert(isequal(measurementModel.C, [1, 0]), ...
                'validateMeasurementModel:InvalidMoldOnlyC', ...
                ['For observabilityCase "moldOnly", measurementModel.C must ', ...
                 'equal [1, 0].']);

            assert(isequal(measurementModel.D, zeros(1, 2)), ...
                'validateMeasurementModel:InvalidMoldOnlyD', ...
                ['For observabilityCase "moldOnly", measurementModel.D must ', ...
                 'equal zeros(1,2).']);
    end
end