function validateNonlinearClosedLoopFullStateResult(simulationResult, closedLoopAnalysisPlan)
    % VALIDATENONLINEARCLOSEDLOOPFULLSTATERESULT Validates simulation result
    % produced by simulateNonlinearClosedLoopFullState.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % INPUTS
    %  simulationResult        (struct) - simulation output struct
    %  closedLoopAnalysisPlan  (struct) - source plan used for simulation
    %
    % OUTPUT
    %  None. Function throws assertion error on invalid input.

    %%%%%%%%%%%%%%%%%%%%%
    % TOP-LEVEL CHECKS  %
    %%%%%%%%%%%%%%%%%%%%%
    assert(isstruct(simulationResult), ...
        'validateNonlinearClosedLoopFullStateResult:InvalidType', ...
        'simulationResult must be a struct.');

    requiredTopLevelFields = {'timestamps', 'state', 'u', 'd', 'evaluator'};
    actualTopLevelFields = fieldnames(simulationResult);

    assert(all(isfield(simulationResult, requiredTopLevelFields)), ...
        'validateNonlinearClosedLoopFullStateResult:MissingField', ...
        ['simulationResult is missing one or more required fields: ', ...
         'timestamps, state, u, d, evaluator.']);

    assert(numel(actualTopLevelFields) == numel(requiredTopLevelFields), ...
        'validateNonlinearClosedLoopFullStateResult:UnexpectedFieldCount', ...
        'simulationResult contains unexpected top-level fields.');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % SOURCE PLAN SANITY CHECKS   %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    assert(isstruct(closedLoopAnalysisPlan), ...
        'validateNonlinearClosedLoopFullStateResult:InvalidPlanType', ...
        'closedLoopAnalysisPlan must be a struct.');

    requiredPlanFields = {'evaluator', 'duration', 'initialConditions'};
    assert(all(isfield(closedLoopAnalysisPlan, requiredPlanFields)), ...
        'validateNonlinearClosedLoopFullStateResult:PlanMissingField', ...
        ['closedLoopAnalysisPlan must contain fields evaluator, duration, ', ...
         'and initialConditions.']);

    validateattributes(closedLoopAnalysisPlan.duration, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'scalar', 'nonnegative'}, ...
        mfilename, 'closedLoopAnalysisPlan.duration');

    assert(isstruct(closedLoopAnalysisPlan.initialConditions), ...
        'validateNonlinearClosedLoopFullStateResult:InvalidInitialConditionsType', ...
        'closedLoopAnalysisPlan.initialConditions must be a struct.');

    assert(isfield(closedLoopAnalysisPlan.initialConditions, 'x0'), ...
        'validateNonlinearClosedLoopFullStateResult:InitialConditionsMissingField', ...
        'closedLoopAnalysisPlan.initialConditions must contain field x0.');

    validateattributes(closedLoopAnalysisPlan.initialConditions.x0, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [2, 1]}, ...
        mfilename, 'closedLoopAnalysisPlan.initialConditions.x0');

    %%%%%%%%%%%%%%%%%%%%%%%
    % TIMESTAMP VALIDATION %
    %%%%%%%%%%%%%%%%%%%%%%%
    validateattributes(simulationResult.timestamps, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'column', 'nonempty'}, ...
        mfilename, 'simulationResult.timestamps');

    timestamps = simulationResult.timestamps;
    numTimestamps = size(timestamps, 1);

    assert(numTimestamps >= 2, ...
        'validateNonlinearClosedLoopFullStateResult:TooFewTimestamps', ...
        'simulationResult.timestamps must contain at least two timestamps.');

    assert(abs(timestamps(1)) < 1e-12, ...
        'validateNonlinearClosedLoopFullStateResult:InvalidStartTime', ...
        'simulationResult.timestamps must start at t = 0.');

    assert(all(diff(timestamps) > 0), ...
        'validateNonlinearClosedLoopFullStateResult:NonMonotoneTimestamps', ...
        'simulationResult.timestamps must be strictly increasing.');

    assert(timestamps(end) <= closedLoopAnalysisPlan.duration + 1e-10, ...
        'validateNonlinearClosedLoopFullStateResult:TimestampExceedsDuration', ...
        ['Final timestamp must not exceed closedLoopAnalysisPlan.duration ', ...
         'beyond numerical tolerance.']);

    %%%%%%%%%%%%%%%%%%%
    % STATE VALIDATION %
    %%%%%%%%%%%%%%%%%%%
    assert(isstruct(simulationResult.state), ...
        'validateNonlinearClosedLoopFullStateResult:InvalidStateType', ...
        'simulationResult.state must be a struct.');

    requiredStateFields = {'x', 'xDot'};
    actualStateFields = fieldnames(simulationResult.state);

    assert(all(isfield(simulationResult.state, requiredStateFields)), ...
        'validateNonlinearClosedLoopFullStateResult:MissingStateField', ...
        'simulationResult.state must contain fields x and xDot.');

    assert(numel(actualStateFields) == numel(requiredStateFields), ...
        'validateNonlinearClosedLoopFullStateResult:UnexpectedStateFieldCount', ...
        'simulationResult.state contains unexpected fields.');

    validateattributes(simulationResult.state.x, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [numTimestamps, 2]}, ...
        mfilename, 'simulationResult.state.x');

    validateattributes(simulationResult.state.xDot, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [numTimestamps, 2]}, ...
        mfilename, 'simulationResult.state.xDot');

    %%%%%%%%%%%%%%%%%%%
    % INPUT VALIDATION %
    %%%%%%%%%%%%%%%%%%%
    validateattributes(simulationResult.u, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [numTimestamps, 2]}, ...
        mfilename, 'simulationResult.u');

    %%%%%%%%%%%%%%%%%%%%%%%%%
    % DISTURBANCE VALIDATION %
    %%%%%%%%%%%%%%%%%%%%%%%%%
    validateattributes(simulationResult.d, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [numTimestamps, 3]}, ...
        mfilename, 'simulationResult.d');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % INITIAL CONDITION CONSISTENCY     %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    x0Expected = closedLoopAnalysisPlan.initialConditions.x0(:);
    x0Observed = simulationResult.state.x(1, :).';

    assert(max(abs(x0Observed - x0Expected)) < 1e-10, ...
        'validateNonlinearClosedLoopFullStateResult:InitialConditionMismatch', ...
        ['First simulated state must match ', ...
         'closedLoopAnalysisPlan.initialConditions.x0 within tolerance.']);

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % BASIC SHAPE / NUMERICAL SANITY     %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    assert(all(isfinite(simulationResult.state.x(:))), ...
        'validateNonlinearClosedLoopFullStateResult:NonFiniteState', ...
        'simulationResult.state.x contains non-finite values.');

    assert(all(isfinite(simulationResult.state.xDot(:))), ...
        'validateNonlinearClosedLoopFullStateResult:NonFiniteStateDerivative', ...
        'simulationResult.state.xDot contains non-finite values.');

    assert(all(isfinite(simulationResult.u(:))), ...
        'validateNonlinearClosedLoopFullStateResult:NonFiniteInput', ...
        'simulationResult.u contains non-finite values.');

    assert(all(isfinite(simulationResult.d(:))), ...
        'validateNonlinearClosedLoopFullStateResult:NonFiniteDisturbance', ...
        'simulationResult.d contains non-finite values.');
end