function validateEquilibrium(equilibrium, operatingPoint)
    % VALIDATEEQUILIBRIUM Validates equilibrium struct produced by
    % getEquilibriumFromOperatingPoint.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % INPUTS
    %  equilibrium    (struct) - equilibrium state/input struct
    %  operatingPoint (struct) - operating point used to construct equilibrium
    %
    % OUTPUT
    %  None. Function throws assertion error on invalid input.

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % OPERATING POINT VALIDATION  %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    assert(isstruct(operatingPoint), ...
        'validateEquilibrium:InvalidOperatingPointType', ...
        'operatingPoint must be a struct.');

    requiredOperatingPointFields = {'K', 'vW', 'hT', 'hM', 'Qladle', 'uM'};
    actualOperatingPointFields = fieldnames(operatingPoint);

    assert(all(isfield(operatingPoint, requiredOperatingPointFields)), ...
        'validateEquilibrium:MissingOperatingPointField', ...
        ['operatingPoint is missing one or more required fields: ', ...
         'K, vW, hT, hM, Qladle, uM.']);

    assert(numel(actualOperatingPointFields) == numel(requiredOperatingPointFields), ...
        'validateEquilibrium:UnexpectedOperatingPointFieldCount', ...
        'operatingPoint contains unexpected fields.');

    for iField = 1:numel(requiredOperatingPointFields)
        fieldName = requiredOperatingPointFields{iField};
        validateattributes(operatingPoint.(fieldName), {'double'}, ...
            {'real', 'finite', 'nonsparse', 'scalar'}, ...
            mfilename, ['operatingPoint.', fieldName]);
    end

    %%%%%%%%%%%%%%%%%%%%%%%%%
    % EQUILIBRIUM VALIDATION %
    %%%%%%%%%%%%%%%%%%%%%%%%%
    assert(isstruct(equilibrium), ...
        'validateEquilibrium:InvalidEquilibriumType', ...
        'equilibrium must be a struct.');

    requiredEquilibriumFields = {'xe', 'ue'};
    actualEquilibriumFields = fieldnames(equilibrium);

    assert(all(isfield(equilibrium, requiredEquilibriumFields)), ...
        'validateEquilibrium:MissingEquilibriumField', ...
        'equilibrium must contain fields xe and ue.');

    assert(numel(actualEquilibriumFields) == numel(requiredEquilibriumFields), ...
        'validateEquilibrium:UnexpectedEquilibriumFieldCount', ...
        'equilibrium contains unexpected fields.');

    validateattributes(equilibrium.xe, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [2, 1]}, ...
        mfilename, 'equilibrium.xe');

    validateattributes(equilibrium.ue, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [2, 1]}, ...
        mfilename, 'equilibrium.ue');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % CONTRACT CONSISTENCY CHECKS %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    expectedXe = [operatingPoint.hT; operatingPoint.hM];
    expectedUe = [operatingPoint.Qladle; operatingPoint.uM];

    assert(isequal(equilibrium.xe, expectedXe), ...
        'validateEquilibrium:StateEquilibriumMismatch', ...
        ['equilibrium.xe must equal [operatingPoint.hT; operatingPoint.hM] ', ...
         'in canonical state ordering.']);

    assert(isequal(equilibrium.ue, expectedUe), ...
        'validateEquilibrium:InputEquilibriumMismatch', ...
        ['equilibrium.ue must equal [operatingPoint.Qladle; operatingPoint.uM] ', ...
         'in canonical input ordering.']);
end