function validateStateFeedbackController(stateFeedbackController, linearPlant, ...
    operatingPoint, stateFeedbackControllerParameters)
% VALIDATESTATEFEEDBACKCONTROLLER Validates state feedback controller struct.
%
% AUTHOR: Cole H. Shaigec
%
% INPUTS
%  stateFeedbackController        (struct) - controller produced by
%                                           buildStateFeedbackController
%  linearPlant                    (struct) - linear plant model
%  operatingPoint                 (struct) - operating point used for design
%  stateFeedbackControllerParameters (struct) - controller design parameters
%
% OUTPUT
%  None. Function throws assertion error on invalid input.

    %%%%%%%%%%%%%%%%%%%%%
    % TOP-LEVEL CHECKS  %
    %%%%%%%%%%%%%%%%%%%%%
    assert(isstruct(stateFeedbackController), ...
        'validateStateFeedbackController:InvalidType', ...
        'stateFeedbackController must be a struct.');

    requiredTopLevelFields = {'type', 'gains', 'equilibrium', 'designMetadata'};
    actualTopLevelFields = fieldnames(stateFeedbackController);

    assert(all(isfield(stateFeedbackController, requiredTopLevelFields)), ...
        'validateStateFeedbackController:MissingField', ...
        ['stateFeedbackController is missing one or more required fields: ', ...
         'type, gains, equilibrium, designMetadata.']);

    assert(numel(actualTopLevelFields) == numel(requiredTopLevelFields), ...
        'validateStateFeedbackController:UnexpectedFieldCount', ...
        'stateFeedbackController contains unexpected top-level fields.');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % INPUT CONTRACT SANITY CHECK %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    assert(isstruct(linearPlant), ...
        'validateStateFeedbackController:InvalidLinearPlantType', ...
        'linearPlant must be a struct.');

    assert(all(isfield(linearPlant, {'A', 'B'})), ...
        'validateStateFeedbackController:LinearPlantMissingField', ...
        'linearPlant must contain fields A and B.');

    validateattributes(linearPlant.A, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [2, 2]}, ...
        mfilename, 'linearPlant.A');

    validateattributes(linearPlant.B, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [2, 2]}, ...
        mfilename, 'linearPlant.B');

    assert(isstruct(operatingPoint), ...
        'validateStateFeedbackController:InvalidOperatingPointType', ...
        'operatingPoint must be a struct.');

    requiredOperatingPointFields = {'K', 'vW', 'hT', 'hM', 'Qladle', 'uM'};
    assert(all(isfield(operatingPoint, requiredOperatingPointFields)), ...
        'validateStateFeedbackController:OperatingPointMissingField', ...
        ['operatingPoint must contain fields K, vW, hT, hM, Qladle, ', ...
         'and uM.']);

    assert(isstruct(stateFeedbackControllerParameters), ...
        'validateStateFeedbackController:InvalidParametersType', ...
        'stateFeedbackControllerParameters must be a struct.');

    assert(isfield(stateFeedbackControllerParameters, 'desiredPoles'), ...
        'validateStateFeedbackController:MissingDesiredPoles', ...
        'stateFeedbackControllerParameters must contain field desiredPoles.');

    validateattributes(stateFeedbackControllerParameters.desiredPoles, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'vector', 'numel', 2}, ...
        mfilename, 'stateFeedbackControllerParameters.desiredPoles');

    desiredPolesReference = stateFeedbackControllerParameters.desiredPoles(:);

    %%%%%%%%%%%%%%%%%%%%%
    % TYPE VALIDATION   %
    %%%%%%%%%%%%%%%%%%%%%
    assert(ischar(stateFeedbackController.type) || isstring(stateFeedbackController.type), ...
        'validateStateFeedbackController:InvalidControllerTypeFieldType', ...
        'stateFeedbackController.type must be a character vector or string scalar.');

    controllerType = string(stateFeedbackController.type);

    assert(isscalar(controllerType) && strlength(controllerType) > 0, ...
        'validateStateFeedbackController:InvalidControllerTypeShape', ...
        'stateFeedbackController.type must be a nonempty string scalar.');

    assert(controllerType == "stateFeedback", ...
        'validateStateFeedbackController:UnsupportedControllerType', ...
        'stateFeedbackController.type must equal "stateFeedback".');

    %%%%%%%%%%%%%%%%%%%%%
    % GAIN VALIDATION   %
    %%%%%%%%%%%%%%%%%%%%%
    validateattributes(stateFeedbackController.gains, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [2, 2]}, ...
        mfilename, 'stateFeedbackController.gains');

    %%%%%%%%%%%%%%%%%%%%%%%%%
    % EQUILIBRIUM VALIDATION %
    %%%%%%%%%%%%%%%%%%%%%%%%%
    equilibrium = stateFeedbackController.equilibrium;

    assert(isstruct(equilibrium), ...
        'validateStateFeedbackController:InvalidEquilibriumType', ...
        'stateFeedbackController.equilibrium must be a struct.');

    requiredEquilibriumFields = {'xe', 'ue'};
    actualEquilibriumFields = fieldnames(equilibrium);

    assert(all(isfield(equilibrium, requiredEquilibriumFields)), ...
        'validateStateFeedbackController:MissingEquilibriumField', ...
        'stateFeedbackController.equilibrium must contain fields xe and ue.');

    assert(numel(actualEquilibriumFields) == numel(requiredEquilibriumFields), ...
        'validateStateFeedbackController:UnexpectedEquilibriumFieldCount', ...
        'stateFeedbackController.equilibrium contains unexpected fields.');

    validateattributes(equilibrium.xe, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'vector', 'numel', 2}, ...
        mfilename, 'stateFeedbackController.equilibrium.xe');

    validateattributes(equilibrium.ue, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'vector', 'numel', 2}, ...
        mfilename, 'stateFeedbackController.equilibrium.ue');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % DESIGN METADATA VALIDATION %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    designMetadata = stateFeedbackController.designMetadata;

    assert(isstruct(designMetadata), ...
        'validateStateFeedbackController:InvalidDesignMetadataType', ...
        'stateFeedbackController.designMetadata must be a struct.');

    requiredDesignMetadataFields = {'Acl', 'desiredPoles', 'placedPoles'};
    actualDesignMetadataFields = fieldnames(designMetadata);

    assert(all(isfield(designMetadata, requiredDesignMetadataFields)), ...
        'validateStateFeedbackController:MissingDesignMetadataField', ...
        ['stateFeedbackController.designMetadata must contain fields ', ...
         'Acl, desiredPoles, and placedPoles.']);

    assert(numel(actualDesignMetadataFields) == numel(requiredDesignMetadataFields), ...
        'validateStateFeedbackController:UnexpectedDesignMetadataFieldCount', ...
        'stateFeedbackController.designMetadata contains unexpected fields.');

    validateattributes(designMetadata.Acl, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [2, 2]}, ...
        mfilename, 'stateFeedbackController.designMetadata.Acl');

    validateattributes(designMetadata.desiredPoles, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'vector', 'numel', 2}, ...
        mfilename, 'stateFeedbackController.designMetadata.desiredPoles');

    % placedPoles may be complex in general, so do NOT require "real"
    validateattributes(designMetadata.placedPoles, {'double'}, ...
        {'finite', 'nonsparse', 'vector', 'numel', 2}, ...
        mfilename, 'stateFeedbackController.designMetadata.placedPoles');

    desiredPolesStored = designMetadata.desiredPoles(:);
    placedPolesStored = designMetadata.placedPoles(:);
    placedPolesFromAcl = eig(designMetadata.Acl);

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % INTERNAL CONSISTENCY CHECKS     %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    assert(isequal(desiredPolesStored, desiredPolesReference), ...
        'validateStateFeedbackController:DesiredPolesMismatch', ...
        ['stateFeedbackController.designMetadata.desiredPoles must exactly ', ...
         'match stateFeedbackControllerParameters.desiredPoles.']);

    % Check that placedPoles matches eig(Acl), up to ordering
    assert(isequal(sort(placedPolesStored), sort(placedPolesFromAcl)), ...
        'validateStateFeedbackController:PlacedPolesMismatch', ...
        ['stateFeedbackController.designMetadata.placedPoles must match ', ...
         'eig(stateFeedbackController.designMetadata.Acl), up to ordering.']);

    % Check closed-loop matrix consistency with plant and gains
    expectedAcl = linearPlant.A - linearPlant.B * stateFeedbackController.gains;
    assert(isequal(size(expectedAcl), [2, 2]), ...
        'validateStateFeedbackController:InternalDimensionFailure', ...
        'Computed expected closed-loop matrix has invalid dimensions.');

    assert(max(abs(designMetadata.Acl - expectedAcl), [], 'all') < 1e-10, ...
        'validateStateFeedbackController:AclMismatch', ...
        ['stateFeedbackController.designMetadata.Acl must equal ', ...
         'linearPlant.A - linearPlant.B * stateFeedbackController.gains.']);

    expectedXe = [operatingPoint.hM; operatingPoint.hT];
    expectedUe = [operatingPoint.uM; operatingPoint.vW];

    assert(isequal(equilibrium.xe(:), expectedXe), ...
        'validateStateFeedbackController:StateEquilibriumMismatch', ...
        ['stateFeedbackController.equilibrium.xe must match the state ', ...
         'equilibrium implied by operatingPoint.']);

    assert(isequal(equilibrium.ue(:), expectedUe), ...
        'validateStateFeedbackController:InputEquilibriumMismatch', ...
        ['stateFeedbackController.equilibrium.ue must match the input ', ...
         'equilibrium implied by operatingPoint.']);
end