function validateLinearPlantControllabilityAnalysis(controllability, linearPlant)
    % VALIDATELINEARPLANTCONTROLLABILITYANALYSIS Validates controllability
    % analysis struct produced by analyzeLinearPlantControllability.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % INPUTS
    %  controllability (struct) - controllability analysis result
    %  linearPlant     (struct) - linear plant model
    %
    % OUTPUT
    %  None. Function throws assertion error on invalid input.

    %%%%%%%%%%%%%%%%%%%%%
    % INPUT SANITY CHECK %
    %%%%%%%%%%%%%%%%%%%%%
    assert(isstruct(linearPlant), ...
        'validateLinearPlantControllabilityAnalysis:InvalidLinearPlantType', ...
        'linearPlant must be a struct.');

    requiredLinearPlantFields = {'A', 'B', 'E', 'metadata'};
    assert(all(isfield(linearPlant, requiredLinearPlantFields)), ...
        'validateLinearPlantControllabilityAnalysis:LinearPlantMissingField', ...
        'linearPlant must contain fields A, B, E, and metadata.');

    validateattributes(linearPlant.A, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [2, 2]}, ...
        mfilename, 'linearPlant.A');

    validateattributes(linearPlant.B, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [2, 2]}, ...
        mfilename, 'linearPlant.B');

    %%%%%%%%%%%%%%%%%%%%%
    % TOP-LEVEL CHECKS  %
    %%%%%%%%%%%%%%%%%%%%%
    assert(isstruct(controllability), ...
        'validateLinearPlantControllabilityAnalysis:InvalidType', ...
        'controllability must be a struct.');

    requiredTopLevelFields = { ...
        'controllabilityMatrix', ...
        'controllabilityMatrixRank', ...
        'isControllable'};

    actualTopLevelFields = fieldnames(controllability);

    assert(all(isfield(controllability, requiredTopLevelFields)), ...
        'validateLinearPlantControllabilityAnalysis:MissingField', ...
        ['controllability is missing one or more required fields: ', ...
         'controllabilityMatrix, controllabilityMatrixRank, isControllable.']);

    assert(numel(actualTopLevelFields) == numel(requiredTopLevelFields), ...
        'validateLinearPlantControllabilityAnalysis:UnexpectedFieldCount', ...
        'controllability contains unexpected top-level fields.');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % CONTROLLABILITY MATRIX CHECKS %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    validateattributes(controllability.controllabilityMatrix, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [2, 4]}, ...
        mfilename, 'controllability.controllabilityMatrix');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % REPORTED RANK VALIDATION    %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    validateattributes(controllability.controllabilityMatrixRank, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'scalar', 'integer', '>=', 0, '<=', 2}, ...
        mfilename, 'controllability.controllabilityMatrixRank');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % BOOLEAN FLAG VALIDATION     %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    assert(islogical(controllability.isControllable) && isscalar(controllability.isControllable), ...
        'validateLinearPlantControllabilityAnalysis:InvalidIsControllableType', ...
        'controllability.isControllable must be a logical scalar.');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % INTERNAL CONSISTENCY AGAINST LINEAR PLANT  %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    A = linearPlant.A;
    B = linearPlant.B;

    expectedControllabilityMatrix = [B, A * B];
    expectedRank = rank(expectedControllabilityMatrix);
    expectedIsControllable = (expectedRank == size(A, 1));

    assert(max(abs(controllability.controllabilityMatrix - expectedControllabilityMatrix), [], 'all') < 1e-10, ...
        'validateLinearPlantControllabilityAnalysis:ControllabilityMatrixMismatch', ...
        ['controllability.controllabilityMatrix must equal [B, A*B] ', ...
         'for the supplied linearPlant.']);

    assert(controllability.controllabilityMatrixRank == expectedRank, ...
        'validateLinearPlantControllabilityAnalysis:RankMismatch', ...
        ['controllability.controllabilityMatrixRank must match ', ...
         'rank(controllability.controllabilityMatrix).']);

    assert(controllability.isControllable == expectedIsControllable, ...
        'validateLinearPlantControllabilityAnalysis:IsControllableMismatch', ...
        ['controllability.isControllable must be true if and only if ', ...
         'the controllability matrix has full row rank.']);
end