function validateLinearPlantObservabilityAnalysis(observability, linearPlant, measurementModel)
    % VALIDATELINEARPLANTOBSERVABILITYANALYSIS Validates observability
    % analysis struct produced by analyzeLinearPlantObservability.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % INPUTS
    %  observability    (struct) - observability analysis result
    %  linearPlant      (struct) - linear plant model
    %  measurementModel (struct) - measurement model
    %
    % OUTPUT
    %  None. Function throws assertion error on invalid input.

    %%%%%%%%%%%%%%%%%%%%%
    % INPUT SANITY CHECK %
    %%%%%%%%%%%%%%%%%%%%%
    assert(isstruct(linearPlant), ...
        'validateLinearPlantObservabilityAnalysis:InvalidLinearPlantType', ...
        'linearPlant must be a struct.');

    requiredLinearPlantFields = {'A', 'B', 'E', 'metadata'};
    assert(all(isfield(linearPlant, requiredLinearPlantFields)), ...
        'validateLinearPlantObservabilityAnalysis:LinearPlantMissingField', ...
        'linearPlant must contain fields A, B, E, and metadata.');

    validateattributes(linearPlant.A, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'size', [2, 2]}, ...
        mfilename, 'linearPlant.A');

    assert(isstruct(measurementModel), ...
        'validateLinearPlantObservabilityAnalysis:InvalidMeasurementModelType', ...
        'measurementModel must be a struct.');

    requiredMeasurementModelFields = {'observabilityCase', 'C', 'D'};
    assert(all(isfield(measurementModel, requiredMeasurementModelFields)), ...
        'validateLinearPlantObservabilityAnalysis:MeasurementModelMissingField', ...
        'measurementModel must contain fields observabilityCase, C, and D.');

    assert(ischar(measurementModel.observabilityCase) || isstring(measurementModel.observabilityCase), ...
        'validateLinearPlantObservabilityAnalysis:InvalidObservabilityCaseType', ...
        'measurementModel.observabilityCase must be a character vector or string scalar.');

    observabilityCase = string(measurementModel.observabilityCase);

    assert(isscalar(observabilityCase) && strlength(observabilityCase) > 0, ...
        'validateLinearPlantObservabilityAnalysis:InvalidObservabilityCaseShape', ...
        'measurementModel.observabilityCase must be a nonempty string scalar.');

    allowedObservabilityCases = ["full", "moldOnly"];
    assert(any(observabilityCase == allowedObservabilityCases), ...
        'validateLinearPlantObservabilityAnalysis:UnsupportedObservabilityCase', ...
        'measurementModel.observabilityCase must be either "full" or "moldOnly".');

    validateattributes(measurementModel.C, {'double'}, ...
        {'real', 'finite', 'nonsparse', '2d'}, ...
        mfilename, 'measurementModel.C');

    %%%%%%%%%%%%%%%%%%%%%
    % TOP-LEVEL CHECKS  %
    %%%%%%%%%%%%%%%%%%%%%
    assert(isstruct(observability), ...
        'validateLinearPlantObservabilityAnalysis:InvalidType', ...
        'observability must be a struct.');

    requiredTopLevelFields = { ...
        'observabilityMatrix', ...
        'observabilityMatrixRank', ...
        'isObservable'};

    actualTopLevelFields = fieldnames(observability);

    assert(all(isfield(observability, requiredTopLevelFields)), ...
        'validateLinearPlantObservabilityAnalysis:MissingField', ...
        ['observability is missing one or more required fields: ', ...
         'observabilityMatrix, observabilityMatrixRank, isObservable.']);

    assert(numel(actualTopLevelFields) == numel(requiredTopLevelFields), ...
        'validateLinearPlantObservabilityAnalysis:UnexpectedFieldCount', ...
        'observability contains unexpected top-level fields.');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % REPORTED RANK VALIDATION    %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    validateattributes(observability.observabilityMatrixRank, {'double'}, ...
        {'real', 'finite', 'nonsparse', 'scalar', 'integer', '>=', 0, '<=', 2}, ...
        mfilename, 'observability.observabilityMatrixRank');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % BOOLEAN FLAG VALIDATION     %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    assert(islogical(observability.isObservable) && isscalar(observability.isObservable), ...
        'validateLinearPlantObservabilityAnalysis:InvalidIsObservableType', ...
        'observability.isObservable must be a logical scalar.');

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % OBSERVABILITY MATRIX SHAPE / CONSISTENCY %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    A = linearPlant.A;
    C = measurementModel.C;

    expectedObservabilityMatrix = [C; C * A];
    expectedRank = rank(expectedObservabilityMatrix);
    expectedIsObservable = (expectedRank == size(A, 1));

    switch observabilityCase
        case "full"
            validateattributes(C, {'double'}, ...
                {'size', [2, 2]}, ...
                mfilename, 'measurementModel.C');

            validateattributes(observability.observabilityMatrix, {'double'}, ...
                {'real', 'finite', 'nonsparse', 'size', [4, 2]}, ...
                mfilename, 'observability.observabilityMatrix');

        case "moldOnly"
            validateattributes(C, {'double'}, ...
                {'size', [1, 2]}, ...
                mfilename, 'measurementModel.C');

            validateattributes(observability.observabilityMatrix, {'double'}, ...
                {'real', 'finite', 'nonsparse', 'size', [2, 2]}, ...
                mfilename, 'observability.observabilityMatrix');
    end

    assert(max(abs(observability.observabilityMatrix - expectedObservabilityMatrix), [], 'all') < 1e-10, ...
        'validateLinearPlantObservabilityAnalysis:ObservabilityMatrixMismatch', ...
        ['observability.observabilityMatrix must equal [C; C*A] ', ...
         'for the supplied linearPlant and measurementModel.']);

    assert(observability.observabilityMatrixRank == expectedRank, ...
        'validateLinearPlantObservabilityAnalysis:RankMismatch', ...
        ['observability.observabilityMatrixRank must match ', ...
         'rank(observability.observabilityMatrix).']);

    assert(observability.isObservable == expectedIsObservable, ...
        'validateLinearPlantObservabilityAnalysis:IsObservableMismatch', ...
        ['observability.isObservable must be true if and only if ', ...
         'the observability matrix has rank equal to the number of states.']);
end