function validatePlottingPlan(plottingPlan, simulationResults, allRunsMetrics)
    % VALIDATEPLOTTINGPLAN Validates plotting plan against available simulation results.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % INPUTS
    %  plottingPlan struct with fields
    %      .trajectories struct with fields
    %          .enabled (logical)
    %          .moldLevel (logical)
    %          .tundishLevel (logical)
    %          .input (logical)
    %          .disturbance (logical)
    %      .comparisons struct with fields
    %          .enabled (logical)
    %          .stateFeedbackVsLQR (logical)
    %          .linearVsNonlinear (logical)
    %      .observer struct with fields
    %          .enabled (logical)
    %          .xHatTrajectory (logical)
    %          .estimationErrorNormTrajectory (logical)
    %      .phasePortraits struct with fields
    %          .enabled (logical)
    %          .linear (logical)
    %          .nonlinear (logical)
    %      .summary struct with fields
    %          .enabled (logical)
    %          .fractionOutsidePrimaryBand (logical)
    %          .fractionOutsideSevereBand (logical)
    %          .peakMoldDeviation (logical)
    %          .controlEnergy (logical)
    %          .peakDeviationControlEnergyScatter (logical)
    %
    %  simulationResults (1 x numRuns struct) - simulation result bundle for all runs
    %  allRunsMetrics (1 x numRuns struct)    - run-level metrics for all runs
    %
    % NOTES
    % - This validator checks that the plotting plan is structurally valid
    % and logically consistent with the available simulation results.
    % - Family-level lower-order toggles are ignored when the corresponding
    % .enabled field is false, and are therefore not treated as invalid.
    % - This utility raises an error if a requested plot type cannot be
    % generated from the available experiment results.

    % -- Basic input validation --
    assert(isstruct(plottingPlan) && isscalar(plottingPlan), ...
        'validatePlottingPlan:InvalidPlottingPlanType', ...
        'plottingPlan must be a scalar struct.');

    assert(isstruct(simulationResults), ...
        'validatePlottingPlan:InvalidSimulationResultsType', ...
        'simulationResults must be a struct array.');

    assert(isstruct(allRunsMetrics), ...
        'validatePlottingPlan:InvalidAllRunsMetricsType', ...
        'allRunsMetrics must be a struct array.');

    assert(~isempty(simulationResults), ...
        'validatePlottingPlan:EmptySimulationResults', ...
        'simulationResults must not be empty.');

    assert(numel(simulationResults) == numel(allRunsMetrics), ...
        'validatePlottingPlan:RunMetricCountMismatch', ...
        'simulationResults and allRunsMetrics must contain the same number of runs.');

    % -- Validate plottingPlan schema and logical field types --
    requiredTrajectoryFields = {'enabled', 'moldLevel', 'tundishLevel', 'input', 'disturbance'};
    requiredComparisonFields = {'enabled', 'stateFeedbackVsLQR', 'linearVsNonlinear'};
    requiredObserverFields = {'enabled', 'xHatTrajectory', 'estimationErrorNormTrajectory'};
    requiredPhasePortraitFields = {'enabled', 'linear', 'nonlinear'};
    requiredSummaryFields = {'enabled', 'fractionOutsidePrimaryBand', ...
        'fractionOutsideSevereBand', 'peakMoldDeviation', ...
        'controlEnergy', 'peakDeviationControlEnergyScatter'};

    assert(isfield(plottingPlan, 'trajectories') && isstruct(plottingPlan.trajectories), ...
        'validatePlottingPlan:MissingTrajectoriesStruct', ...
        'plottingPlan.trajectories must exist and be a struct.');
    assert(isfield(plottingPlan, 'comparisons') && isstruct(plottingPlan.comparisons), ...
        'validatePlottingPlan:MissingComparisonsStruct', ...
        'plottingPlan.comparisons must exist and be a struct.');
    assert(isfield(plottingPlan, 'observer') && isstruct(plottingPlan.observer), ...
        'validatePlottingPlan:MissingObserverStruct', ...
        'plottingPlan.observer must exist and be a struct.');
    assert(isfield(plottingPlan, 'phasePortraits') && isstruct(plottingPlan.phasePortraits), ...
        'validatePlottingPlan:MissingPhasePortraitsStruct', ...
        'plottingPlan.phasePortraits must exist and be a struct.');
    assert(isfield(plottingPlan, 'summary') && isstruct(plottingPlan.summary), ...
        'validatePlottingPlan:MissingSummaryStruct', ...
        'plottingPlan.summary must exist and be a struct.');

    validateLogicalSubstruct(plottingPlan.trajectories, requiredTrajectoryFields, 'trajectories');
    validateLogicalSubstruct(plottingPlan.comparisons, requiredComparisonFields, 'comparisons');
    validateLogicalSubstruct(plottingPlan.observer, requiredObserverFields, 'observer');
    validateLogicalSubstruct(plottingPlan.phasePortraits, requiredPhasePortraitFields, 'phasePortraits');
    validateLogicalSubstruct(plottingPlan.summary, requiredSummaryFields, 'summary');

    % -- Determine what kinds of runs are present --
    numRuns = numel(simulationResults);

    controllerTypes = strings(numRuns, 1);
    observabilityCases = strings(numRuns, 1);
    hasAnyLinearResult = false;
    hasAnyNonlinearResult = false;
    hasAnyObserverRun = false;

    for iRun = 1:numRuns
        thisRun = simulationResults(iRun);

        controllerTypes(iRun) = string(thisRun.controller.type);
        observabilityCases(iRun) = string(thisRun.observabilityCase);

        hasAnyLinearResult = hasAnyLinearResult || ...
            (isfield(thisRun, 'linearClosedLoopResult') && ~isempty(thisRun.linearClosedLoopResult));

        hasAnyNonlinearResult = hasAnyNonlinearResult || ...
            (isfield(thisRun, 'nonlinearClosedLoopResult') && ~isempty(thisRun.nonlinearClosedLoopResult));

        hasAnyObserverRun = hasAnyObserverRun || strcmp(thisRun.observabilityCase, 'moldOnly');
    end

    hasStateFeedbackRuns = any(strcmp(controllerTypes, 'stateFeedback'));
    hasLQRRuns = any(strcmp(controllerTypes, 'lqr'));

    % -- Validate trajectory requests --
    if plottingPlan.trajectories.enabled
        hasAnyTrajectoryPlotEnabled = plottingPlan.trajectories.moldLevel || ...
            plottingPlan.trajectories.tundishLevel || ...
            plottingPlan.trajectories.input || ...
            plottingPlan.trajectories.disturbance;

        assert(hasAnyTrajectoryPlotEnabled, ...
            'validatePlottingPlan:EmptyTrajectoryFamily', ...
            ['plottingPlan.trajectories.enabled is true, but no trajectory ' ...
             'plot types are enabled within that family.']);

        assert(hasAnyLinearResult || hasAnyNonlinearResult, ...
            'validatePlottingPlan:NoTrajectoryDataAvailable', ...
            'Trajectory plots were requested, but no closed-loop trajectory data is available.');
    end

    % -- Validate comparison requests --
    if plottingPlan.comparisons.enabled
        hasAnyComparisonEnabled = plottingPlan.comparisons.stateFeedbackVsLQR || ...
            plottingPlan.comparisons.linearVsNonlinear;

        assert(hasAnyComparisonEnabled, ...
            'validatePlottingPlan:EmptyComparisonFamily', ...
            ['plottingPlan.comparisons.enabled is true, but no comparison ' ...
             'plot types are enabled within that family.']);

        if plottingPlan.comparisons.stateFeedbackVsLQR
            assert(hasStateFeedbackRuns && hasLQRRuns, ...
                'validatePlottingPlan:MissingControllerTypesForComparison', ...
                ['State-feedback-versus-LQR comparison was requested, but ' ...
                 'the experiment set does not contain at least one state-feedback ' ...
                 'run and one LQR run.']);
        end

        if plottingPlan.comparisons.linearVsNonlinear
            assert(hasAnyLinearResult && hasAnyNonlinearResult, ...
                'validatePlottingPlan:MissingPlantTypesForComparison', ...
                ['Linear-versus-nonlinear comparison was requested, but the ' ...
                 'available simulation results do not contain both linear and ' ...
                 'nonlinear closed-loop results.']);
        end
    end

    % -- Validate observer requests --
    if plottingPlan.observer.enabled
        hasAnyObserverPlotEnabled = plottingPlan.observer.xHatTrajectory || ...
            plottingPlan.observer.estimationErrorNormTrajectory;

        assert(hasAnyObserverPlotEnabled, ...
            'validatePlottingPlan:EmptyObserverFamily', ...
            ['plottingPlan.observer.enabled is true, but no observer plot ' ...
             'types are enabled within that family.']);

        assert(hasAnyObserverRun, ...
            'validatePlottingPlan:ObserverPlotsRequestedWithoutObserverRuns', ...
            ['Observer plots were requested, but all runs use full-state ' ...
             'observability. No xHat trajectories are available to plot.']);

        % Sanity-check that observer runs actually contain xHat
        for iRun = 1:numRuns
            if strcmp(simulationResults(iRun).observabilityCase, 'moldOnly')
                assert(isfield(simulationResults(iRun).linearClosedLoopResult.state, 'xHat'), ...
                    'validatePlottingPlan:MissingLinearXHat', ...
                    'Observer plotting requires linearClosedLoopResult.state.xHat for moldOnly runs.');
                assert(isfield(simulationResults(iRun).nonlinearClosedLoopResult.state, 'xHat'), ...
                    'validatePlottingPlan:MissingNonlinearXHat', ...
                    'Observer plotting requires nonlinearClosedLoopResult.state.xHat for moldOnly runs.');
            end
        end
    end

    % -- Validate phase portrait requests --
    if plottingPlan.phasePortraits.enabled
        hasAnyPhasePortraitEnabled = plottingPlan.phasePortraits.linear || ...
            plottingPlan.phasePortraits.nonlinear;

        assert(hasAnyPhasePortraitEnabled, ...
            'validatePlottingPlan:EmptyPhasePortraitFamily', ...
            ['plottingPlan.phasePortraits.enabled is true, but no phase ' ...
             'portrait plot types are enabled within that family.']);

        if plottingPlan.phasePortraits.linear
            assert(hasAnyLinearResult, ...
                'validatePlottingPlan:MissingLinearResultsForPhasePortraits', ...
                'Linear phase portraits were requested, but no linear closed-loop results are available.');
        end

        if plottingPlan.phasePortraits.nonlinear
            assert(hasAnyNonlinearResult, ...
                'validatePlottingPlan:MissingNonlinearResultsForPhasePortraits', ...
                'Nonlinear phase portraits were requested, but no nonlinear closed-loop results are available.');
        end
    end

    % -- Validate summary plot requests --
    if plottingPlan.summary.enabled
        hasAnySummaryPlotEnabled = plottingPlan.summary.fractionOutsidePrimaryBand || ...
            plottingPlan.summary.fractionOutsideSevereBand || ...
            plottingPlan.summary.peakMoldDeviation || ...
            plottingPlan.summary.controlEnergy || ...
            plottingPlan.summary.peakDeviationControlEnergyScatter;

        assert(hasAnySummaryPlotEnabled, ...
            'validatePlottingPlan:EmptySummaryFamily', ...
            ['plottingPlan.summary.enabled is true, but no summary plot ' ...
             'types are enabled within that family.']);

        assert(~isempty(allRunsMetrics), ...
            'validatePlottingPlan:MissingMetricsForSummaryPlots', ...
            'Summary plots were requested, but allRunsMetrics is empty.');

        % Check that the required summary metrics exist in every run
        for iRun = 1:numRuns
            assert(isfield(allRunsMetrics(iRun), 'linear') && isfield(allRunsMetrics(iRun), 'nonlinear'), ...
                'validatePlottingPlan:MalformedRunMetrics', ...
                'Each element of allRunsMetrics must contain .linear and .nonlinear structs.');

            validateSummaryMetricFields(allRunsMetrics(iRun).linear, ...
                plottingPlan.summary, 'linear', iRun);
            validateSummaryMetricFields(allRunsMetrics(iRun).nonlinear, ...
                plottingPlan.summary, 'nonlinear', iRun);
        end
    end
end

function validateLogicalSubstruct(substructIn, requiredFields, substructName)
    for iField = 1:numel(requiredFields)
        thisField = requiredFields{iField};

        assert(isfield(substructIn, thisField), ...
            'validatePlottingPlan:MissingPlottingPlanField', ...
            'plottingPlan.%s.%s is missing.', substructName, thisField);

        assert(islogical(substructIn.(thisField)) && isscalar(substructIn.(thisField)), ...
            'validatePlottingPlan:InvalidLogicalField', ...
            'plottingPlan.%s.%s must be a scalar logical.', substructName, thisField);
    end
end

function validateSummaryMetricFields(metricStruct, summaryPlan, metricStructName, runIndex)
    if summaryPlan.fractionOutsidePrimaryBand
        assert(isfield(metricStruct, 'fractionOutsidePrimaryBand'), ...
            'validatePlottingPlan:MissingFractionOutsidePrimaryBand', ...
            'Run %d is missing %s.fractionOutsidePrimaryBand.', runIndex, metricStructName);
    end

    if summaryPlan.fractionOutsideSevereBand
        assert(isfield(metricStruct, 'fractionInSevereBandViolation'), ...
            'validatePlottingPlan:MissingFractionInSevereBandViolation', ...
            'Run %d is missing %s.fractionInSevereBandViolation.', runIndex, metricStructName);
    end

    if summaryPlan.peakMoldDeviation || summaryPlan.peakDeviationControlEnergyScatter
        assert(isfield(metricStruct, 'maxAbsoluteMoldLevelDeviation'), ...
            'validatePlottingPlan:MissingMaxAbsoluteMoldLevelDeviation', ...
            'Run %d is missing %s.maxAbsoluteMoldLevelDeviation.', runIndex, metricStructName);
    end

    if summaryPlan.controlEnergy || summaryPlan.peakDeviationControlEnergyScatter
        assert(isfield(metricStruct, 'controlEnergy'), ...
            'validatePlottingPlan:MissingControlEnergy', ...
            'Run %d is missing %s.controlEnergy.', runIndex, metricStructName);
    end
end