function nonlinearPlantPhasePortraitPlot = plotNonlinearPlantPhasePortrait( ...
    nonlinearPhasePortraitData, nonlinearPhasePortraitDisplaySpec)
    % PLOTNONLINEARPLANTPHASEPORTRAIT Plots nonlinear-plant state trajectory in the state plane.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % INPUTS
    %  nonlinearPhasePortraitData struct with fields
    %      .x (numTimestamps x 2 double) - simulated state trajectory
    %      .xe (2 x 1 double)            - equilibrium state
    %
    %  nonlinearPhasePortraitDisplaySpec struct with fields
    %      .title (string)
    %      .xLabel (string)
    %      .yLabel (string)
    %      .legendEntries (cell array of strings)
    %
    % OUTPUT
    %  nonlinearPlantPhasePortraitPlot (figure handle)

    nonlinearPlantPhasePortraitPlot = figure('Visible', 'off');
    hold on;
    grid on;

    stateTrajectory = plot( ...
        nonlinearPhasePortraitData.x(:, 1), ...
        nonlinearPhasePortraitData.x(:, 2), ...
        'b');

    initialState = plot( ...
        nonlinearPhasePortraitData.x(1, 1), ...
        nonlinearPhasePortraitData.x(1, 2), ...
        'go', ...
        'MarkerFaceColor', 'g');

    finalState = plot( ...
        nonlinearPhasePortraitData.x(end, 1), ...
        nonlinearPhasePortraitData.x(end, 2), ...
        'ro', ...
        'MarkerFaceColor', 'r');

    equilibriumState = plot( ...
        nonlinearPhasePortraitData.xe(1), ...
        nonlinearPhasePortraitData.xe(2), ...
        'kx', ...
        'MarkerSize', 10, ...
        'LineWidth', 1.5);

    title(nonlinearPhasePortraitDisplaySpec.title);
    xlabel(nonlinearPhasePortraitDisplaySpec.xLabel);
    ylabel(nonlinearPhasePortraitDisplaySpec.yLabel);

    if ~isempty(nonlinearPhasePortraitDisplaySpec.legendEntries)
        legend( ...
            [stateTrajectory, initialState, finalState, equilibriumState], ...
            nonlinearPhasePortraitDisplaySpec.legendEntries, ...
            'Location', 'best');
    end
end