function phasePortraitPlot = plotPlantPhasePortrait( ...
    phasePortraitData, phasePortraitDisplaySpec, evaluator)
    % PLOTPLANTPHASEPORTRAIT Plots phase portrait for a given plant.
    %
    % AUTHOR: Cole H. Shaigec

    phasePortraitPlot = figure('Visible', 'off');
    hold on;
    grid on;
    box on;

    plotVectorField(phasePortraitData, evaluator);

    stateTrajectory = plot( ...
        phasePortraitData.x(:, 1), ...
        phasePortraitData.x(:, 2), ...
        'Color', [0.0000, 0.2000, 0.8000], ...
        'LineWidth', 2.0);

    initialState = plot( ...
        phasePortraitData.x(1, 1), ...
        phasePortraitData.x(1, 2), ...
        'o', ...
        'Color', [0.0000, 0.4500, 0.0000], ...
        'MarkerFaceColor', [0.0000, 0.8000, 0.0000], ...
        'MarkerSize', 7, ...
        'LineWidth', 1.2);

    finalState = plot( ...
        phasePortraitData.x(end, 1), ...
        phasePortraitData.x(end, 2), ...
        'o', ...
        'Color', [0.7000, 0.0000, 0.0000], ...
        'MarkerFaceColor', [1.0000, 0.0000, 0.0000], ...
        'MarkerSize', 7, ...
        'LineWidth', 1.2);

    equilibriumState = plot( ...
        phasePortraitData.xe(1), ...
        phasePortraitData.xe(2), ...
        'x', ...
        'Color', [0.0000, 0.0000, 0.0000], ...
        'MarkerSize', 11, ...
        'LineWidth', 2.0);

    title(phasePortraitDisplaySpec.title);
    xlabel(phasePortraitDisplaySpec.xLabel);
    ylabel(phasePortraitDisplaySpec.yLabel);

    if ~isempty(phasePortraitDisplaySpec.legendEntries)
        legend( ...
            [stateTrajectory, initialState, finalState, equilibriumState], ...
            phasePortraitDisplaySpec.legendEntries, ...
            'Location', 'best');
    end
end

function plotVectorField(phasePortraitData, evaluator)

    assert(isfield(evaluator, 'evaluateStateDerivative'), ...
        'evaluator.evaluateStateDerivative is required.');

    assert(isa(evaluator.evaluateStateDerivative, 'function_handle'), ...
        'evaluator.evaluateStateDerivative must be a function handle.');

    x = phasePortraitData.x;

    x1Min = min([x(:, 1); phasePortraitData.xe(1)]);
    x1Max = max([x(:, 1); phasePortraitData.xe(1)]);
    x2Min = min([x(:, 2); phasePortraitData.xe(2)]);
    x2Max = max([x(:, 2); phasePortraitData.xe(2)]);

    paddingFactor = 0.20;

    x1Range = x1Max - x1Min;
    x2Range = x2Max - x2Min;

    if x1Range == 0
        x1Range = 1;
    end

    if x2Range == 0
        x2Range = 1;
    end

    numGridPoints = 21;

    x1GridVector = linspace( ...
        x1Min - paddingFactor*x1Range, ...
        x1Max + paddingFactor*x1Range, ...
        numGridPoints);

    x2GridVector = linspace( ...
        x2Min - paddingFactor*x2Range, ...
        x2Max + paddingFactor*x2Range, ...
        numGridPoints);

    [x1Grid, x2Grid] = meshgrid(x1GridVector, x2GridVector);

    x1DotGrid = zeros(size(x1Grid));
    x2DotGrid = zeros(size(x2Grid));

    representativeTime = 0;

    if isfield(phasePortraitData, 't') && ~isempty(phasePortraitData.t)
        representativeTime = phasePortraitData.t(1);
    end

    for i = 1:numel(x1Grid)
        state = [x1Grid(i); x2Grid(i)];
        
        % Evaluator is structured differently for different observability
        % cases
        if nargin(evaluator.evaluateStateDerivative) == 2
            stateDerivative = evaluator.evaluateStateDerivative( ...
                representativeTime, state);
        elseif nargin(evaluator.evaluateStateDerivative) == 3
            stateDerivative = evaluator.evaluateStateDerivative( ...
                representativeTime, state, state);
        else
            error('evaluator.evaluateStateDerivative must accept either (t, x) or (t, x, xHat).');
        end

        x1DotGrid(i) = stateDerivative(1);
        x2DotGrid(i) = stateDerivative(2);
    end

    arrowMagnitude = hypot(x1DotGrid, x2DotGrid);
    nonzeroArrowMask = arrowMagnitude > 0;

    x1DotGrid(nonzeroArrowMask) = ...
        x1DotGrid(nonzeroArrowMask) ./ arrowMagnitude(nonzeroArrowMask);

    x2DotGrid(nonzeroArrowMask) = ...
        x2DotGrid(nonzeroArrowMask) ./ arrowMagnitude(nonzeroArrowMask);

    quiver( ...
        x1Grid, ...
        x2Grid, ...
        x1DotGrid, ...
        x2DotGrid, ...
        0.45, ...
        'Color', [0.7500, 0.7500, 0.7500], ...
        'LineWidth', 0.65, ...
        'HandleVisibility', 'off');
end