function linearPlantPhasePortraitPlot = plotLinearPlantPhasePortrait( ...
    linearPhasePortraitData, linearPhasePortraitDisplaySpec)
    % PLOTLINEARPLANTPHASEPORTRAIT Plots linear-plant state trajectory in the state plane.
    %
    % AUTHOR: Cole H. Shaigec
    %
    % INPUTS
    %  linearPhasePortraitData struct with fields
    %      .x (numTimestamps x 2 double) - simulated state trajectory
    %      .xe (2 x 1 double)            - equilibrium state
    %
    %  linearPhasePortraitDisplaySpec struct with fields
    %      .title (string)
    %      .xLabel (string)
    %      .yLabel (string)
    %      .legendEntries (cell array of strings)
    %
    % OUTPUT
    %  linearPlantPhasePortraitPlot (figure handle)

    linearPlantPhasePortraitPlot = figure('Visible', 'off');
    hold on;
    grid on;

    stateTrajectory = plot( ...
        linearPhasePortraitData.x(:, 1), ...
        linearPhasePortraitData.x(:, 2), ...
        'b');

    initialState = plot( ...
        linearPhasePortraitData.x(1, 1), ...
        linearPhasePortraitData.x(1, 2), ...
        'go', ...
        'MarkerFaceColor', 'g');

    finalState = plot( ...
        linearPhasePortraitData.x(end, 1), ...
        linearPhasePortraitData.x(end, 2), ...
        'ro', ...
        'MarkerFaceColor', 'r');

    equilibriumState = plot( ...
        linearPhasePortraitData.xe(1), ...
        linearPhasePortraitData.xe(2), ...
        'kx', ...
        'MarkerSize', 10, ...
        'LineWidth', 1.5);

    title(linearPhasePortraitDisplaySpec.title);
    xlabel(linearPhasePortraitDisplaySpec.xLabel);
    ylabel(linearPhasePortraitDisplaySpec.yLabel);

    if ~isempty(linearPhasePortraitDisplaySpec.legendEntries)
        legend( ...
            [stateTrajectory, initialState, finalState, equilibriumState], ...
            linearPhasePortraitDisplaySpec.legendEntries, ...
            'Location', 'best');
    end
end